# Generated by Django 2.2.15 on 2020-08-27 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='timeframe',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='uid_home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customtext_uid_home', to='home.HomePage'),
        ),
        migrations.AddField(
            model_name='customtext',
            name='user_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='uid_home',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customtext',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
